### ISSUE TITLE
cannot use Mouse Buttons 3-5

### ISSUE THREAD

**Issue by ManuelGraf** [SargoDarya/xiv-rotation-hero#11]
**Current Behavior:**
When reassigning a hotbar key, mouse buttons 3,4,5,.. wont be assigned, and their default action triggers

**Expected Behavior:**
* when reassigning keys in keybindings, please allow to capture additional mouse buttons. (refer to https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button for vendor-specific mouse events )
* default event for those mouse events have to be prevented

**Comment by SargoDarya** [comment]
This slipped through and probably wasn't considered at all yet.
